/*
 * stm32f407xx_rcc_driver.c
 *
 *  Created on: Sep 19, 2026
 *      Author: LEGION
 */

#include "stm32f407xx.h"

uint16_t AHB_PreScaler[8] = {2, 4, 8, 16, 64, 128, 256, 512};
uint16_t APB1_PreScaler[4] = {2, 4, 8, 16};

uint32_t RCC_GetPCLK1Value(void)
{
	uint32_t pclk1;
	uint32_t SystemClk;
	uint8_t clksrc, temp, ahbp, apb1p;

	clksrc = ((RCC->CFGR >> 2) & 0x3);			//shift the CFGR bit to right shift and then bitmask the rest by using AND

	if(clksrc == 0){
		SystemClk = 16000000;
	}else if(clksrc == 1){
		SystemClk = 8000000;
	}else if(clksrc == 2){
		SystemClk = RCC_GetPLLOutputClock();
	}

	//ahbp
	temp = ((RCC->CFGR >> 4) & 0xF);
	if(temp < 8){
		ahbp = 1;
	}else{
		ahbp = AHB_PreScaler[temp-8];
	}

	//apb1p
	temp = ((RCC->CFGR >> 10) & 0x7);
	if(temp < 4){
		apb1p = 1;
	}else{
		apb1p = APB1_PreScaler[temp-8];
	}

	pclk1 = (SystemClk/ahbp) / apb1p;

	return pclk1;
}

uint32_t RCC_GetPCLK2Value(void)
{
	uint32_t SystemClock=0,tmp,pclk2;
	uint8_t clk_src = ( RCC->CFGR >> 2) & 0X3;

	uint8_t ahbp,apb2p;

	if(clk_src == 0)
	{
		SystemClock = 16000000;
	}else
	{
		SystemClock = 8000000;
	}
	tmp = (RCC->CFGR >> 4 ) & 0xF;

	if(tmp < 0x08)
	{
		ahbp = 1;
	}else
	{
       ahbp = AHB_PreScaler[tmp-8];
	}

	tmp = (RCC->CFGR >> 13 ) & 0x7;
	if(tmp < 0x04)
	{
		apb2p = 1;
	}else
	{
		apb2p = APB1_PreScaler[tmp-4];
	}

	pclk2 = (SystemClock / ahbp )/ apb2p;

	return pclk2;
}

uint32_t RCC_GetPLLOutputClock(void){

	//this code is generated by Claude
	uint32_t PLL;
	uint32_t pllvco, pllm, plln, pllp, pllsrc;

	pllsrc = (RCC->PLLCFGR >> 22) & 0x1;			//bit22 : PLL entry clock source (0 = HSI, 1 = HSE)

	pllm = (RCC->PLLCFGR) & 0x3F;				//bits 5:0 : division factor for the main PLL input clock
	plln = (RCC->PLLCFGR >> 6) & 0x1FF;			//bits 14:6 : main PLL multiplication factor for VCO

	pllp = (RCC->PLLCFGR >> 16) & 0x3;			//bits 17:16 : main PLL division factor for main system clock
	pllp = (pllp + 1) * 2;						//00->2, 01->4, 10->6, 11->8

	if(pllsrc == 0){
		pllvco = (16000000 / pllm) * plln;		//HSI = 16MHz
	}else{
		pllvco = (8000000 / pllm) * plln;		//HSE = 8MHz (change if your board uses a different crystal)
	}

	PLL = pllvco / pllp;

	return PLL;
}


