/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407xx.h"


void delay(void)
{
	for(uint32_t i = 0; i < 500000; i++);
}

int main(void)
{
	GPIO_Handle_t GpioLedG, GpioLedO, GpioLedR, GpioLedB;

	GpioLedG.pGPIOx 								= GPIOD;
	GpioLedG.GPIO_PinConfig.GPIO_PinNumber 			= GPIO_PIN_NO_12;
	GpioLedG.GPIO_PinConfig.GPIO_PinMode 			= GPIO_MODE_OUT;
	GpioLedG.GPIO_PinConfig.GPIO_PinSpeed			= GPIO_SPEED_HIGH;
	GpioLedG.GPIO_PinConfig.GPIO_PinOPType			= GPIO_OP_TYPE_PP;
	GpioLedG.GPIO_PinConfig.GPIO_PinPuPdControl 	= GPIO_NO_PUPD;

	GpioLedO.pGPIOx 								= GPIOD;
	GpioLedO.GPIO_PinConfig.GPIO_PinNumber 			= GPIO_PIN_NO_13;
	GpioLedO.GPIO_PinConfig.GPIO_PinMode 			= GPIO_MODE_OUT;
	GpioLedO.GPIO_PinConfig.GPIO_PinSpeed			= GPIO_SPEED_HIGH;
	GpioLedO.GPIO_PinConfig.GPIO_PinOPType			= GPIO_OP_TYPE_PP;
	GpioLedO.GPIO_PinConfig.GPIO_PinPuPdControl 	= GPIO_NO_PUPD;

	GpioLedR.pGPIOx 								= GPIOD;
	GpioLedR.GPIO_PinConfig.GPIO_PinNumber 			= GPIO_PIN_NO_14;
	GpioLedR.GPIO_PinConfig.GPIO_PinMode 			= GPIO_MODE_OUT;
	GpioLedR.GPIO_PinConfig.GPIO_PinSpeed			= GPIO_SPEED_HIGH;
	GpioLedR.GPIO_PinConfig.GPIO_PinOPType			= GPIO_OP_TYPE_PP;
	GpioLedR.GPIO_PinConfig.GPIO_PinPuPdControl 	= GPIO_NO_PUPD;

	GpioLedB.pGPIOx 								= GPIOD;
	GpioLedB.GPIO_PinConfig.GPIO_PinNumber 			= GPIO_PIN_NO_15;
	GpioLedB.GPIO_PinConfig.GPIO_PinMode 			= GPIO_MODE_OUT;
	GpioLedB.GPIO_PinConfig.GPIO_PinSpeed			= GPIO_SPEED_HIGH;
	GpioLedB.GPIO_PinConfig.GPIO_PinOPType			= GPIO_OP_TYPE_PP;
	GpioLedB.GPIO_PinConfig.GPIO_PinPuPdControl 	= GPIO_NO_PUPD;

	GPIO_PeriClockControl(GPIOD, ENABLE);
	GPIO_Init(&GpioLedG);
	GPIO_Init(&GpioLedO);
	GPIO_Init(&GpioLedR);
	GPIO_Init(&GpioLedB);

	while(1)
	{
		GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_12);
		delay();
		GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_13);
		delay();
		GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_14);
		delay();
		GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_15);
		delay();
	}

	return 0;
}
